# Generated by Django 5.0 on 2023-12-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('arms', 'Legs'), ('waist', 'Waist'), ('legs', 'Legs')], max_length=5)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slot1', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])),
                ('slot2', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])),
                ('slot3', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])),
                ('defense', models.IntegerField()),
                ('fire_res', models.IntegerField()),
                ('water_res', models.IntegerField()),
                ('thunder_res', models.IntegerField()),
                ('ice_res', models.IntegerField()),
                ('dragon_res', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('size', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('skill_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('max_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
            ],
        ),
        migrations.CreateModel(
            name='ArmorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armors', to='main_app.armor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_skill_name'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.skill'),
        ),
        migrations.AddField(
            model_name='armorskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main_app.skill'),
        ),
        migrations.AddField(
            model_name='armor',
            name='skills',
            field=models.ManyToManyField(through='main_app.ArmorSkill', to='main_app.skill'),
        ),
        migrations.AddConstraint(
            model_name='decoration',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_decoration_name'),
        ),
        migrations.AddConstraint(
            model_name='armorskill',
            constraint=models.UniqueConstraint(fields=('armor', 'skill'), name='unique_armor_skill'),
        ),
        migrations.AddConstraint(
            model_name='armor',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_armor_name'),
        ),
    ]
