# Generated by Django 5.0 on 2023-12-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_armor_unique_armor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='armor',
            constraint=models.UniqueConstraint(fields=('armorset_id', 'category'), name='unique_armor'),
        ),
    ]
